#! /usr/bin/perl

# Copyright 2015 LouieDogg LLC
my $author = "admin\@louiedogg.com";
# ####################################################################
# Description: Everything is a module
#
# License:GPLv2
#
# ####################################################################
use strict;
use warnings;

																		#############################
																		# RUN MAIN LOOP 		
																		# DOGG HOSPITALITY			
																		#############################
																		
																		######## LIBRARIES ##########																# Current Working Directory
use lib 'dogg';															# Use main/ as a lib
use lib 'dogg/widgets';
use lib 'dogg/web';



sub dogg_run
{
	my $arg_count = @_;
	my $arg_one = shift;
	my $arg_two = shift;
	
	use dogg_main;
	use dogg_cwd;
	use dogg_lib;														# Main Loop Module
	use dogg_json;
	
	# Help menu array
	my @help = (
				"--help			Will display this menu\n",
				"--web			Runs Web Interface\n",
				"--widget 		Runs Widget Interface\n",
				"--rsync 		Rsyncs into production\n",
				"--up-v-sync 	up versions, rsyncs into prod, & pushes repo\n"
				);
					
	if($arg_count == 1)												# Ensure there is just one argument
	{											
		
		if($arg_one eq "--widget")
		{
			dogg_main::main();										# Run the TK Widget
		}
		elsif($arg_one eq "--web")										# Run Web interface
		{
			my @local = ("x-www-browser localhost");
			dogg_main::run_commands(@local);			
		}
		elsif($arg_one eq "--rsync")
		{
			my @rsync = ("rsync -rtvu --delete /home/louiedogg/projects/louiedogg/ /usr/louiedogg/");
			dogg_main::run_commands(@rsync);
		}
		elsif($arg_one eq "--help")
		{
			print @help;
		}
		elsif($arg_one eq "--up-v-sync")
		{
			print "--up-v-r must have to arguments!\n\n";
		}
	}
	if($arg_count == 2)
	{
		if($arg_one eq "--up-v-sync")
		{
			dogg_main::update_version($arg_two);
		}
	}
	if(($arg_count > 2) or ($arg_count ==0))
	{
		print @help;
	}
}

dogg_run(@ARGV);


